### ISSUE TITLE
Random failings of apt installing packages during packer build

### ISSUE THREAD

**Issue by guangie88** [GovTechSG/terraform-modules#169]
Many times when running packer build for Nomad servers fail (likely the same for the other three services), because it is unable to install some package (obviously should be there) such as `gcc`, even though Ansible has stated that apt has already updated the cache and upgraded the state to the latest.

The log looks something like this:

```
    ubuntu-1604-nomad-server-ami:
    ubuntu-1604-nomad-server-ami: PLAY [Provision AMI] ***********************************************************
    ubuntu-1604-nomad-server-ami:
    ubuntu-1604-nomad-server-ami: TASK [Gathering Facts] *********************************************************
    ubuntu-1604-nomad-server-ami: ok: [default]
    ubuntu-1604-nomad-server-ami:
    ubuntu-1604-nomad-server-ami: TASK [Upgrade all packages to the latest version] ******************************
    ubuntu-1604-nomad-server-ami:  [WARNING]: Could not find aptitude. Using apt-get instead.
    ubuntu-1604-nomad-server-ami: changed: [default]

...

    ubuntu-1604-nomad-server-ami: TASK [xxx/terraform-modules/modules/core/packer/nomad_servers/../../../../roles/td-agent : Install dependencies for td-agent] ***
    ubuntu-1604-nomad-server-ami: failed: [default] (item=['gcc', 'make']) => {"changed": false, "item": ["gcc", "make"], "msg": "No package matching 'gcc' is available"}
    ubuntu-1604-nomad-server-ami:       to retry, use: --limit @xxx/terraform-modules/modules/core/packer/nomad_servers/site.retry
    ubuntu-1604-nomad-server-ami:
    ubuntu-1604-nomad-server-ami: PLAY RECAP *********************************************************************
    ubuntu-1604-nomad-server-ami: default                    : ok=5    changed=3    unreachable=0    failed=1
```

**Comment by lawliet89** [comment]
Workaround in #170

**Comment by guangie88** [comment]
The following changes were done to the `site.yml` for `nomad_server` packer build:

```yml
pre_tasks:
  # - name: Upgrade all packages to the latest version
  #   apt:
  #     upgrade: yes
  #     update_cache: yes
  #   become: yes
  - name: Echo /etc/apt/sources.list
    command: cat /etc/apt/sources.list
    register: source1
  - debug: msg="{{ source1.stdout }}"

  - name: Upgrade all packages to the latest version
    shell: "apt update && apt upgrade -y"
    become: yes
    
  - name: Echo cached packages
    command: apt-cache policy
    register: source2
  - debug: msg="{{ source2.stdout }}"
```

There were two possible outcomes with different stdout messages:

## When `gcc` successfully installs

### `cat /etc/apt/sources.list`

```yml
## Note, this file is written by cloud-init on first boot of an instance
## modifications made here will not survive a re-bundle.
## if you wish to make changes you can:
## a.) add 'apt_preserve_sources_list: true' to /etc/cloud/cloud.cfg
##     or do the same in user-data
## b.) add sources in /etc/apt/sources.list.d
## c.) make changes to template file /etc/cloud/templates/sources.list.tmpl

# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/ xenial main restricted
deb-src http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/ xenial main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/ xenial-updates main restricted
deb-src http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/ xenial-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/ xenial universe
deb-src http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/ xenial universe
deb http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/ xenial-updates universe
deb-src http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/ xenial-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu 
## team, and may not be under a free licence. Please satisfy yourself as to 
## your rights to use the software. Also, please note that software in 
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/ xenial multiverse
deb-src http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/ xenial multiverse
deb http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/ xenial-updates multiverse
deb-src http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/ xenial-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOT receive any review
## or updates from the Ubuntu security team.
deb http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse
deb-src http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse

deb http://security.ubuntu.com/ubuntu xenial-security main restricted
deb-src http://security.ubuntu.com/ubuntu xenial-security main restricted
deb http://security.ubuntu.com/ubuntu xenial-security universe
deb-src http://security.ubuntu.com/ubuntu xenial-security universe
deb http://security.ubuntu.com/ubuntu xenial-security multiverse
deb-src http://security.ubuntu.com/ubuntu xenial-security multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu xenial partner
# deb-src http://archive.canonical.com/ubuntu xenial partner
```

### `apt-cache policy`

```yml
Package files:
 100 /var/lib/dpkg/status
     release a=now
 500 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages
     release v=16.04,o=Ubuntu,a=xenial-security,n=xenial,l=Ubuntu,c=multiverse,b=amd64
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages
     release v=16.04,o=Ubuntu,a=xenial-security,n=xenial,l=Ubuntu,c=universe,b=amd64
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages
     release v=16.04,o=Ubuntu,a=xenial-security,n=xenial,l=Ubuntu,c=restricted,b=amd64
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
     release v=16.04,o=Ubuntu,a=xenial-security,n=xenial,l=Ubuntu,c=main,b=amd64
     origin security.ubuntu.com
 100 http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages
     release v=16.04,o=Ubuntu,a=xenial-backports,n=xenial,l=Ubuntu,c=universe,b=amd64
     origin ap-southeast-1.ec2.archive.ubuntu.com
 100 http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu xenial-backports/main amd64 Packages
     release v=16.04,o=Ubuntu,a=xenial-backports,n=xenial,l=Ubuntu,c=main,b=amd64
     origin ap-southeast-1.ec2.archive.ubuntu.com
 500 http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/multiverse amd64 Packages
     release v=16.04,o=Ubuntu,a=xenial-updates,n=xenial,l=Ubuntu,c=multiverse,b=amd64
     origin ap-southeast-1.ec2.archive.ubuntu.com
 500 http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
     release v=16.04,o=Ubuntu,a=xenial-updates,n=xenial,l=Ubuntu,c=universe,b=amd64
     origin ap-southeast-1.ec2.archive.ubuntu.com
 500 http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/restricted amd64 Packages
     release v=16.04,o=Ubuntu,a=xenial-updates,n=xenial,l=Ubuntu,c=restricted,b=amd64
  origin ap-southeast-1.ec2.archive.ubuntu.com
 500 http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
     release v=16.04,o=Ubuntu,a=xenial-updates,n=xenial,l=Ubuntu,c=main,b=amd64
     origin ap-southeast-1.ec2.archive.ubuntu.com
 500 http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu xenial/multiverse amd64 Packages
     release v=16.04,o=Ubuntu,a=xenial,n=xenial,l=Ubuntu,c=multiverse,b=amd64
     origin ap-southeast-1.ec2.archive.ubuntu.com
 500 http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
     release v=16.04,o=Ubuntu,a=xenial,n=xenial,l=Ubuntu,c=universe,b=amd64
     origin ap-southeast-1.ec2.archive.ubuntu.com
 500 http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu xenial/restricted amd64 Packages
     release v=16.04,o=Ubuntu,a=xenial,n=xenial,l=Ubuntu,c=restricted,b=amd64
     origin ap-southeast-1.ec2.archive.ubuntu.com
 500 http://ap-southeast-1.ec2.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
     release v=16.04,o=Ubuntu,a=xenial,n=xenial,l=Ubuntu,c=main,b=amd64
     origin ap-southeast-1.ec2.archive.ubuntu.com
Pinned packages:
```

## When `gcc` has problem installing and has error

### `cat /etc/apt/sources.list`

```yml
# See http://help.ubuntu.com/community/UpgradeNotes for how to upgrade to
# newer versions of the distribution.
deb http://archive.ubuntu.com/ubuntu/ xenial main restricted
# deb-src http://archive.ubuntu.com/ubuntu/ xenial main restricted

## Major bug fix updates produced after the final release of the
## distribution.
deb http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted
# deb-src http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team. Also, please note that software in universe WILL NOT receive any
## review or updates from the Ubuntu security team.
deb http://archive.ubuntu.com/ubuntu/ xenial universe
# deb-src http://archive.ubuntu.com/ubuntu/ xenial universe
deb http://archive.ubuntu.com/ubuntu/ xenial-updates universe
# deb-src http://archive.ubuntu.com/ubuntu/ xenial-updates universe

## N.B. software from this repository is ENTIRELY UNSUPPORTED by the Ubuntu
## team, and may not be under a free licence. Please satisfy yourself as to
## your rights to use the software. Also, please note that software in
## multiverse WILL NOT receive any review or updates from the Ubuntu
## security team.
deb http://archive.ubuntu.com/ubuntu/ xenial multiverse
# deb-src http://archive.ubuntu.com/ubuntu/ xenial multiverse
deb http://archive.ubuntu.com/ubuntu/ xenial-updates multiverse
# deb-src http://archive.ubuntu.com/ubuntu/ xenial-updates multiverse

## N.B. software from this repository may not have been tested as
## extensively as that contained in the main release, although it includes
## newer versions of some applications which may provide useful features.
## Also, please note that software in backports WILL NOTreceive any review
## or updates from the Ubuntu security team.
deb http://archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse
# deb-src http://archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse

## Uncomment the following two lines to add software from Canonical's
## 'partner' repository.
## This software is not part of Ubuntu, but is offered by Canonical and the
## respective vendors as a service to Ubuntu users.
# deb http://archive.canonical.com/ubuntu xenial partner
# deb-src http://archive.canonical.com/ubuntu xenial partner

deb http://security.ubuntu.com/ubuntu/ xenial-security main restricted
# deb-src http://security.ubuntu.com/ubuntu/ xenial-security main restricted
deb http://security.ubuntu.com/ubuntu/ xenial-securityuniverse
# deb-src http://security.ubuntu.com/ubuntu/ xenial-security universe
deb http://security.ubuntu.com/ubuntu/ xenial-security multiverse
# deb-src http://security.ubuntu.com/ubuntu/ xenial-security multiverse
```

### `apt-cache policy`

```yml
Package files:
 100 /var/lib/dpkg/status
     release a=now
 500 http://security.ubuntu.com/ubuntu xenial-security/multiverse amd64 Packages
     release v=16.04,o=Ubuntu,a=xenial-security,n=xenial,l=Ubuntu,c=multiverse,b=amd64
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages
     release v=16.04,o=Ubuntu,a=xenial-security,n=xenial,l=Ubuntu,c=universe,b=amd64
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu xenial-security/restricted amd64 Packages
     release v=16.04,o=Ubuntu,a=xenial-security,n=xenial,l=Ubuntu,c=restricted,b=amd64
     origin security.ubuntu.com
 500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
     release v=16.04,o=Ubuntu,a=xenial-security,n=xenial,l=Ubuntu,c=main,b=amd64
     origin security.ubuntu.com
Pinned packages:
```
